### ISSUE TITLE
Add home-screen icon and shortcut

### ISSUE THREAD

**Issue by ghost** [laingsimon/timestables#19]

**Comment by laingsimon** [comment]
https://web.dev/customize-install/

**Comment by laingsimon** [comment]
https://stackoverflow.com/questions/34369951/how-to-get-add-to-home-screen-pop-up-on-site-open-in-mobile-browser

**Comment by laingsimon** [comment]
https://blog.betapage.co/how-to-add-add-to-homescreen-popup-in-web-app-99d5237fabff#.szght9vpm

**Comment by laingsimon** [comment]
https://medium.com/@sam20gh/how-to-add-add-to-home-screen-to-your-website-4b07aee02676

**Comment by laingsimon** [comment]
https://dev.to/iamsahilsonawane/a2hs-in-flutter-web-3cln

See what chrome (desktop) says under dev tools/application/manifest

**Comment by laingsimon** [comment]
https://web.dev/customize-install/

**Comment by laingsimon** [comment]
> Registers a service worker with a fetch handler

Need to add a fetch handler?
