### ISSUE TITLE
Add prompt/redirect to latest version

### ISSUE THREAD

**Issue by ghost** [laingsimon/timestables#45]
If the app is installed it is tied to that version.
The app should check if there is a later version and prompt to navigate to it.

**Comment by laingsimon** [comment]
In the app, when it launches, make a request to https://app.timestables.xyz/index.html.

Read the content and find the redirect meta header.

If the redirect header is different to the current URL then propose/redirect to the meta header address.

**Comment by laingsimon** [comment]
Get the html...

```javascript
function getHtml(url, callback)
{
    if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp=new XMLHttpRequest();
    }
    else
    {// code for IE6, IE5
        console.log("URL content retrieval not supported");
        return;
    }
    xmlhttp.onreadystatechange=function()
    {
        if (xmlhttp.readyState==4 && xmlhttp.status==200)
        {
            callback(url, xmlhttp.responseText);
        }
    }
    xmlhttp.open("GET", url, false);
    xmlhttp.send();    
}
```

**Comment by laingsimon** [comment]
Related to #48

**Comment by laingsimon** [comment]
Change of plan.

Store text file that is available via the website, e.g. app.timestables.xyz/versions.

The file should contain the directory name of each deployed main branch version. Each version should be record on a individual line, in chronological order, oldest first newest last.

In #48 the file will be used to remove the oldest deployments leaving the most recent ones.

For this change, read the file via the js method above, and use the last line. This will contain the folder name  of the latest version. If the current page doesn't contain this version then a prompt/redirect can be executed.

**Comment by laingsimon** [comment]
Versions file created and available at the above address

**Comment by ghost** [comment]
Prompt is working but using rather ugly browser `confirm` dialogs. These should be improved
